In [1]:
import torch
import pandas as np
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1


##Introduction to Tensors

What is a tensor? Tensors are a way to represent data. Numeric data.

Tensors are created with "torch.tensor()"

In [2]:
#Scalar
scalar = torch.tensor(7)
print (scalar)
scalar.item() # Get tensor back to python int 

tensor(7)


7

In [3]:
#Vectors
Vector = torch.tensor([7,7])
Vector.ndim #Returns the dimention
Vector.shape

torch.Size([2])

In [4]:
#MATRIX
MATRIX = torch.tensor([
                        [7,8],
                        [10,9]
                      ])

MATRIX.shape

torch.Size([2, 2])

In [5]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]
                      ]])
TENSOR.ndim
TENSOR.shape

torch.Size([1, 3, 3])

In [6]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [7]:
#Random tensors, neural networks usualy start with a random tensor.
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6038, 0.1867, 0.6040, 0.9503],
        [0.3057, 0.6594, 0.4751, 0.0029],
        [0.9333, 0.3646, 0.6964, 0.1290]])

In [8]:
#Create a tnesor with a similar shape to an image
random_image = torch.rand(size=(3,224,244))
random_image.shape, random_image.ndim

(torch.Size([3, 224, 244]), 3)

In [9]:
#Zeros and onesin tensors
zero = torch.zeros(size=(3,4))
ones = torch.ones(size=(3,4))

In [10]:
ones.dtype

torch.float32

In [11]:
#Own torch tnesors (Practice)
PZero = torch.zeros(size=(3,4))
POne = torch.ones(size=(3,4))
print (PZero)
print(POne)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [12]:
## Createing a range of tensors and tensors-like

#Use torch.arange()
range = torch.arange(start = 0, end = 1000, step = 77)
range

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [13]:
#Createing tensors like
ten_zeros = torch.zeros_like(input= range)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

##Tensor Datatypes 

**Note** : Tensor datatypes is one of the 3 big issues with PyTorch && deep learnig:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

In [14]:
floatTensor32 = torch.tensor([3.0,4.0,3.9],
                              dtype=torch.float32, #We especify the data type of the tensor
                             device= "cpu",  # We specify the device in which the tensor will run
                             requires_grad= False) #Track Gradients
floatTensor32


tensor([3.0000, 4.0000, 3.9000])

In [15]:
#Convert tensors between bits
floatTensor16 = floatTensor32.type(torch.float16)
floatTensor16

tensor([3.0000, 4.0000, 3.9004], dtype=torch.float16)

In [16]:
floatTensor16 * floatTensor32 #Worked ??!

tensor([ 9.0000, 16.0000, 15.2115])

### Geting information from tensors (Tensor atributes)
1. Tensors not right datatype - to do get datatype from a tensor, can use 'tensor.dtype'
2. Tensors not right shape    - to get shape from a tensor, can use 'tensor.shape'
3. Tensors not on right device  - to get device from tensor, can use 'tensor.device'


In [17]:
#Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4287, 0.2027, 0.5922, 0.2950],
        [0.8488, 0.3987, 0.1429, 0.1628],
        [0.7354, 0.2320, 0.5212, 0.8996]])

In [18]:
#Find out details about some tensor
print (some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.4287, 0.2027, 0.5922, 0.2950],
        [0.8488, 0.3987, 0.1429, 0.1628],
        [0.7354, 0.2320, 0.5212, 0.8996]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulation tensors (Tensor operations)

Tensor operation include:
* Adition 
* Substraction
*Multiplication (element wise)
* Division
* Matrix multiplication

In [19]:
# Create a tensor and add 100 to it
tensor = torch.tensor([1,2,3])
tensor + 100

tensor([101, 102, 103])

In [20]:
# Multiply tensor by 100
tensor * 100


tensor([100, 200, 300])

In [21]:
#Subtract 100
tensor - 1000

tensor([-999, -998, -997])

In [22]:
# Try pyTorch in-build functions
torch.mul(tensor,100)

tensor([100, 200, 300])

In [23]:
torch.add(tensor,100)

tensor([101, 102, 103])

### Matrix multiplication

Two main way to perform multiplications in neural network and deep learning: 

1. Element-wise multiplication
2. Matrix multiplication (Dot Product)

2 Rules:
  1. Inner dimentions must match ( (2,3) @ (2,3) no)  ( (3,2) @ (2,3) yes)

In [24]:
#Element wise multiplication

print ("tensor *, tensor")
print (f"Equals: {tensor * tensor}")

tensor *, tensor
Equals: tensor([1, 4, 9])


In [25]:
#Matrx multiplication
torch.matmul(tensor,tensor)

tensor(14)

## One of the most common errors in deep learning: shape errors

In [26]:
#Shapes for matrix multiplications
tensor_A = torch.tensor([[1,2,3],
                         [4,5,6],
                         [7,8,9]])

tensor_B = torch.tensor([[3,4],
                         [5,6],
                         [6,5]])

torch.mm(tensor_A,tensor_B) # torch.mm is a alias for torch.matmul

tensor([[ 31,  31],
        [ 73,  76],
        [115, 121]])

To fix out tensor shepe issues, we can transpose the tensors.

In [27]:
tensor_B.T

tensor([[3, 5, 6],
        [4, 6, 5]])

## Finding the min, max, mean, sum, etc. (tensor aggregation)

In [28]:
#Create a tensor
x = torch.arange(0,100,10, dtype= torch.float32)
print (x)

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])


In [29]:
#Find the min
torch.min(x)

tensor(0.)

In [30]:
#Find the Max
torch.max(x)

tensor(90.)

In [31]:
#Find the mean, it requires a tensor of float32 datatype to work
torch.mean(x)

tensor(45.)

In [32]:
#Find the sum
torch.sum(x), x.sum()

(tensor(450.), tensor(450.))

## Finding the positional min and max

In [33]:
x.argmin()

tensor(0)

In [34]:
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - Combin multiple tensors on top of each other (Vstack) or side by side (hstack)
* Squeeze -removes all '1' dimentions form a tensor
* Unsqueeze - add a '1' dimension toa  target tensor
* Permute - Return a view of the input with dimention permuted (Swapped) in a certain way

In [54]:
import torch
x = torch.arange(1.,10.)
x , x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [51]:
#Add en extra dimention
x_reshaped = x.reshape(5,2)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [56]:
# Change the view 
z = x.view(1,9)
z

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [57]:
#Changinh z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z ,x 

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [73]:
#Stack tensors on top of eah other
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[[[[[0., 0.]],

           [[0., 0.]]]],



         [[[[0., 0.]],

           [[0., 0.]]]],



         [[[[0., 0.]],

           [[0., 0.]]]],



         [[[[0., 0.]],

           [[0., 0.]]]]],




        [[[[[0., 0.]],

           [[0., 0.]]]],



         [[[[0., 0.]],

           [[0., 0.]]]],



         [[[[0., 0.]],

           [[0., 0.]]]],



         [[[[0., 0.]],

           [[0., 0.]]]]]])

In [74]:
#torch.squeeze()
x_reshaped


tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [75]:
x_reshaped.shape

torch.Size([5, 2])

In [103]:
x = torch.arange(0,9)
x = x.reshape(3,3)

(tensor([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]),
 tensor([[[0],
          [1],
          [2]],
 
         [[3],
          [4],
          [5]],
 
         [[6],
          [7],
          [8]]]))

In [90]:
#torch.unsqueeze() - adds a single dimention to a targer tensora at a specific dim (Dimention)
x , x.unsqueeze(2)

In [113]:
#torch.pemute - rearranges the dimentions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) # [height, width, colour_channels]
x_original[0][0][0] = 45933980


In [121]:
#Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1)# shifts axis to 0 -> 1, 1 -> 2 , 2 -> 0
x_permuted[0,0,0]

tensor(45933980.)

## Indexing (Selectiong data form tensors)

Indexing with PyTorch is similar to indexing with pytorch

In [125]:
#Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x , x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [126]:
#Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [131]:
#Let's index in the middle bracket (dim 1)
x[0][0]

tensor([1, 2, 3])

In [132]:
#Let's index on the most inner bracket (Last dimention)
x[0][0][0]

tensor(1)

In [137]:
#You can also use ":" to select "all" of the target dimention
x[0][:][0]

tensor([1, 2, 3])

In [139]:
#Get all values of 0 and 1 dimention but only index 1 of the second dimention
x[0][:][1]


tensor([4, 5, 6])

###PyTorch tensors & Numpy 

Numpy is a popular scientific Python numerical computing library.

And because of this, Pytorch has functionality to interact with it.

* Data in Numpy, want in PyThon tensor -> 'torch.from_numpy(ndarray)'
* PyTorch tensor -> NumPy -> 'torch.Tensor.numpy()'

In [5]:
#Numpy array to tensor

import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) # Warning when converting numpy -> pythorch reflects numpy's default datatype of float 64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [6]:
#Change the valuie of array, what w8ill this do to 'tensor'
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [3]:
array.dtype

torch.float64

In [4]:
tensor.dtype

torch.float64

In [8]:
#Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
numpy_tensor

array([1., 1., 1., 1., 1., 1., 1.], dtype=float32)

## Reproducbility (tying to take random out of random)

In short howe a neural network learns:

`Start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and pyTorch and NumPy comes the concept of a **Random seed**.

Essencially wht the random seeds does is "Flavor" the randomness.

In [19]:
import torch

#Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8463, 0.1010, 0.1026, 0.2454],
        [0.1814, 0.2673, 0.6109, 0.5673],
        [0.5414, 0.9358, 0.2213, 0.5583]])
tensor([[0.9929, 0.6014, 0.4313, 0.7937],
        [0.3225, 0.6420, 0.6088, 0.5362],
        [0.1242, 0.9092, 0.3971, 0.9298]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [20]:
# Let's make some random but reproducible tensors

import torch

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED) # It only works for 1 block o code

random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)

random_tensor_D = torch.rand(3,4)

print(random_tensor_C == random_tensor_D)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making it faster)